alter table public.castaways add column if not exists social_state jsonb not null default '{"relationships":{},"intent":{"type":"survive","targetId":null,"reason":"Reach tomorrow"},"promises":[],"secrets":[]}'::jsonb;
alter table public.game_log add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.simulation_events (
  id bigint generated by default as identity primary key,
  season_id integer not null references public.seasons(id) on delete cascade,
  day integer not null,
  event_key text not null,
  phase text not null,
  type text not null,
  actor_ids integer[] not null default '{}',
  target_ids integer[] not null default '{}',
  cause text not null,
  visibility text not null check (visibility in ('public','private','confessional')),
  text text not null,
  deltas jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (season_id, event_key)
);
create index if not exists simulation_events_season_day_idx on public.simulation_events(season_id, day, id);
alter table public.simulation_events enable row level security;
revoke all on public.simulation_events from anon, authenticated;
grant select on public.simulation_events to anon, authenticated;
create policy simulation_events_public_read on public.simulation_events for select to anon, authenticated using (visibility = 'public');

create table if not exists public.social_alliances (
  id bigint generated by default as identity primary key,
  season_id integer not null references public.seasons(id) on delete cascade,
  day integer not null,
  alliance_key text not null,
  leader_id integer references public.castaways(id) on delete set null,
  member_ids integer[] not null default '{}',
  target_id integer references public.castaways(id) on delete set null,
  cohesion numeric not null default 0,
  status text not null default 'active' check (status in ('active','fractured','resolved')),
  created_at timestamptz not null default now(),
  unique (season_id, day, alliance_key)
);
alter table public.social_alliances enable row level security;
revoke all on public.social_alliances from anon, authenticated;
grant select on public.social_alliances to anon, authenticated;
create policy social_alliances_public_read on public.social_alliances for select to anon, authenticated using (true);

create table if not exists public.audience_focus (
  user_id uuid not null references public.profiles(id) on delete cascade,
  season_id integer not null references public.seasons(id) on delete cascade,
  day integer not null,
  castaway_id integer not null references public.castaways(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, season_id, day)
);
alter table public.audience_focus enable row level security;
revoke all on public.audience_focus from anon;
grant select, insert, update, delete on public.audience_focus to authenticated;
create policy audience_focus_owner_select on public.audience_focus for select to authenticated using ((select auth.uid()) = user_id);
create policy audience_focus_owner_insert on public.audience_focus for insert to authenticated with check ((select auth.uid()) = user_id);
create policy audience_focus_owner_update on public.audience_focus for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy audience_focus_owner_delete on public.audience_focus for delete to authenticated using ((select auth.uid()) = user_id);

create table if not exists public.signal_questions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  season_id integer not null references public.seasons(id) on delete cascade,
  day integer not null,
  castaway_id integer not null references public.castaways(id) on delete cascade,
  prompt_key text not null check (prompt_key in ('trust','threat','regret','plan')),
  answer text,
  created_at timestamptz not null default now(),
  unique (user_id, season_id, day)
);
alter table public.signal_questions enable row level security;
revoke all on public.signal_questions from anon;
revoke all on public.signal_questions from authenticated;
grant select on public.signal_questions to authenticated;
create policy signal_questions_owner_select on public.signal_questions for select to authenticated using ((select auth.uid()) = user_id);
